// <auto-generated />
namespace BLL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class AddalltablesinDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddalltablesinDB));
        
        string IMigrationMetadata.Id
        {
            get { return "201502241557500_Add all tables in DB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
